---
- hosts: localhost
  vars:
    cp_management_ip: "{{lookup('env','cp_mgmt_ip')}}"
    cp_management_user: "{{lookup('env','cp_mgmt_user')}}"
    cp_management_pass: "{{lookup('env','cp_mgmt_pass')}}"
    cp_management_fingerprint: "{{lookup('env','cp_mgmt_fingerprint')}}"

  tasks:
  - name: "Check Point Management API - Login"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{ cp_management_user }}"
        password: "{{ cp_management_pass }}"
        management: "{{ cp_management_ip }}"
      fingerprint: "{{ cp_management_fingerprint }}"
    register: login_response

  - name: "Check Point Management API - Show Hosts"
    check_point_mgmt:
      command: show-hosts
      parameters:
        details-level: standard
      session-data: "{{ login_response }}"
    register: hosts

  - name: "Debug Message - Show Hosts Output"
    debug:
      msg: "{{ hosts }}"

  - name: "Check Point Management API - Logout"
    check_point_mgmt:
      command: logout
      session-data: "{{ login_response }}"

