---
- hosts: localhost
  vars:
    cp_management_ip: "{{lookup('env','cp_mgmt_ip')}}"
    cp_management_user: "{{lookup('env','cp_mgmt_user')}}"
    cp_management_pass: "{{lookup('env','cp_mgmt_pass')}}"
    cp_management_fingerprint: "{{lookup('env','cp_mgmt_fingerprint')}}"

  tasks:

  - name: "Check Point Management API - Login"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{ cp_management_user }}"
        password: "{{ cp_management_pass }}"
        management: "{{ cp_management_ip }}"
      fingerprint: "{{ cp_management_fingerprint }}"
    register: login_response

  - name: "Check Point Management API - Add NAT Rule"
    check_point_mgmt:
      command: add-nat-rule
      parameters:
        package: Standard
        position: top
        comments: "comment example"
        original-source: any
        original-destination: All_Internet
        original-service: "ssh"
        translated-service: "http"
      session-data: "{{ login_response }}"

  - name: "Check Point Management API - Publish"
    check_point_mgmt:
      command: publish
      session-data: "{{ login_response }}"

  - name: "Check Point Management API - Logout"
    check_point_mgmt:
      command: logout
      session-data: "{{ login_response }}"

